#!/usr/bin/env python3
"""Generate a canonical project health snapshot for Cumination."""

from __future__ import annotations

import datetime as dt
import re
import xml.etree.ElementTree as ET
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SITES_DIR = ROOT / "plugin.video.cumination" / "resources" / "lib" / "sites"
TESTS_DIR = ROOT / "tests"
ADDON_XML = ROOT / "plugin.video.cumination" / "addon.xml"
CHANGELOG = ROOT / "plugin.video.cumination" / "changelog.txt"
KNOWN_ISSUES = ROOT / "docs" / "development" / "KNOWN_ISSUES.md"
OUTPUT = ROOT / "docs" / "development" / "PROJECT_HEALTH.md"

BS_MARKERS = (
    "utils.parse_html(",
    "BeautifulSoup(",
    ".select(",
    ".select_one(",
)

REGEX_MARKERS = (
    "re.compile(",
    "re.findall(",
    "re.finditer(",
)


def list_sites() -> list[dict[str, object]]:
    sites = []
    for path in sorted(SITES_DIR.glob("*.py")):
        if path.name.startswith("__") or path.name == "soup_spec.py":
            continue
        text = path.read_text(encoding="utf-8", errors="ignore")
        uses_bs4 = any(marker in text for marker in BS_MARKERS)
        uses_regex = any(marker in text for marker in REGEX_MARKERS)
        sites.append(
            {
                "name": path.stem,
                "path": path,
                "uses_bs4": uses_bs4,
                "uses_regex": uses_regex,
            }
        )
    return sites


def collect_tested_sites() -> set[str]:
    tested = set()
    for path in sorted((TESTS_DIR / "sites").glob("test_*.py")):
        site_name = path.stem.removeprefix("test_")
        if site_name:
            tested.add(site_name)

    smoke_dir = TESTS_DIR / "smoke_generated"
    if smoke_dir.exists():
        for path in sorted(smoke_dir.glob("test_smoke_*.py")):
            site_name = path.stem.removeprefix("test_smoke_")
            if site_name:
                tested.add(site_name)

    return tested


def read_versions() -> tuple[str, str]:
    addon_tree = ET.parse(ADDON_XML)
    addon_root = addon_tree.getroot()
    addon_version = addon_root.attrib.get("version", "unknown")

    changelog_text = CHANGELOG.read_text(encoding="utf-8", errors="ignore")
    match = re.search(r"\[B\]Version\s+([0-9][^\[]+)\[/B\]", changelog_text)
    changelog_version = match.group(1).strip() if match else "unknown"
    return addon_version, changelog_version


def parse_known_issues(limit: int = 10) -> list[tuple[str, str]]:
    issues_text = KNOWN_ISSUES.read_text(encoding="utf-8", errors="ignore")
    issues: list[tuple[str, str]] = []
    for line in issues_text.splitlines():
        line = line.strip()
        m = re.match(r"^-\s+\*\*(.+?)\*\*\s+[–-]\s+(.+)$", line)
        if m:
            issues.append((m.group(1).strip(), m.group(2).strip()))
        if len(issues) >= limit:
            break
    return issues


def build_markdown() -> str:
    sites = list_sites()
    tested_sites = collect_tested_sites()
    addon_version, changelog_version = read_versions()
    issues = parse_known_issues(limit=10)

    total_sites = len(sites)
    migrated_sites = [s for s in sites if s["uses_bs4"]]
    tested_count = sum(1 for s in sites if s["name"] in tested_sites)

    timestamp = dt.datetime.now(dt.timezone.utc).replace(microsecond=0).isoformat()

    lines = [
        "# Project Health",
        "",
        "_This document is generated by `scripts/generate_project_health.py`. Do not edit manually._",
        "",
        f"- **Last generated (UTC)**: {timestamp}",
        f"- **Release version (addon.xml)**: `{addon_version}`",
        f"- **Latest changelog version**: `{changelog_version}`",
        "",
        "## Summary",
        "",
        f"- **Total site count**: {total_sites}",
        f"- **Migrated count (BeautifulSoup markers)**: {len(migrated_sites)}",
        f"- **Tested count (tests/sites + tests/smoke_generated)**: {tested_count}",
        "",
        "## Top broken / known issue sites",
        "",
    ]

    if issues:
        for site, desc in issues:
            lines.append(f"- **{site}** — {desc}")
    else:
        lines.append(
            "- No known issue bullets detected in `docs/development/KNOWN_ISSUES.md`."
        )

    lines.extend(
        [
            "",
            "## Site inventory",
            "",
            "| Site | BeautifulSoup marker | Regex marker | Has per-site tests |",
            "|---|---:|---:|---:|",
        ]
    )

    for site in sites:
        name = str(site["name"])
        bs = "✅" if site["uses_bs4"] else "❌"
        rx = "✅" if site["uses_regex"] else "❌"
        tested = "✅" if name in tested_sites else "❌"
        lines.append(f"| `{name}` | {bs} | {rx} | {tested} |")

    lines.append("")
    return "\n".join(lines)


def main() -> None:
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(build_markdown(), encoding="utf-8")
    print(f"Wrote {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
